# Generated by Django 5.1.3 on 2025-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0002_userwavesafetyzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwavesafetyzone",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="userwavesafetyzone",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
