# Generated by Django 5.1.3 on 2025-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_alter_userwavesafetyzone_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactstrigger',
            name='phone_number_hashed',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
