# Generated by Django 5.1.3 on 2025-08-14 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0004_alter_usercontactstrigger_phone_number_hashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontactstrigger",
            name="phone_number_hashed",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="usercontactstrigger",
            unique_together={("user", "phone_number_hashed")},
        ),
    ]
