# Generated by Django 5.1.3 on 2024-12-03 08:38

import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySession',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryHistory',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_by', to='location.discoverysession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered', to='location.discoverysession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
