# Generated by Django 5.1.3 on 2024-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_discoverysession_discoveryhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryhistory",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoveryhistory",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoveryhistory",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoveryhistory",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
