# Generated by Django 5.1.3 on 2025-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0003_discoveryhistory_accuracy_discoveryhistory_altitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
