# Generated by Django 5.1.3 on 2025-03-22 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_userlocation_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlocation",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="location",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
