# Generated by Django 5.1.3 on 2025-08-20 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_alter_userlocation_options_alter_userlocation_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discoveryhistory",
            index=models.Index(
                fields=["session", "discovered"], name="location_di_session_7b1e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryhistory",
            index=models.Index(
                fields=["created_at"], name="location_di_created_4d8c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryhistory",
            index=models.Index(
                fields=["updated_at"], name="location_di_updated_a7491a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoverysession",
            index=models.Index(
                fields=["user", "is_active"], name="location_di_user_id_886c7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(fields=["user"], name="location_us_user_id_08d50c_idx"),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["created_at"], name="location_us_created_7647f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["updated_at"], name="location_us_updated_526c00_idx"
            ),
        ),
    ]
