# Generated by Django 5.1.3 on 2025-09-16 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_discoveryhistory_location_di_session_7b1e70_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='geohash',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['geohash'], name='location_us_geohash_8d53c6_idx'),
        ),
    ]
