# Generated by Django 5.1.3 on 2025-09-16 09:14

import django.db.models.deletion
import flitz.models
import location.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_userlocation_geohash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocationHistory",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("geohash", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "indexes": [
                    models.Index(
                        fields=["user"], name="location_us_user_id_9e357e_idx"
                    ),
                    models.Index(
                        fields=["geohash"], name="location_us_geohash_4b4cf8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="location_us_created_c5cb27_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="location_us_updated_900d20_idx"
                    ),
                ],
            },
            bases=(models.Model, location.models.LocationDistanceMixin),
        ),
    ]
