# Generated by Django 5.1.3 on 2025-09-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0008_userlocationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocationhistory",
            name="is_in_safety_zone",
            field=models.BooleanField(default=False),
        ),
    ]
