# Generated by Django 5.1.3 on 2025-09-19 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0009_userlocationhistory_is_in_safety_zone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["timezone"], name="location_us_timezon_a1aaf0_idx"
            ),
        ),
    ]
