# Generated by Django 5.1.3 on 2025-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="apns_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
