# Generated by Django 5.1.3 on 2025-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_alter_usersession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="token_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
