# Generated by Django 5.1.3 on 2024-11-24 08:56

import flitz.models
import uuid_v7.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('content', models.JSONField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardDistribution',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardFlag',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=128)),
                ('user_description', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardVote',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote_type', models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialCardAsset',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(max_length=32)),
                ('object_key', models.CharField(max_length=2048)),
                ('public_url', models.CharField(max_length=2048)),
                ('mimetype', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialCardAssetAuthor',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialCardAssetGroup',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('free', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialCardAssetPurchase',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCardAsset',
            fields=[
                ('id', flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
                ('object_key', models.CharField(max_length=2048)),
                ('public_url', models.CharField(max_length=2048)),
                ('mimetype', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
