# Generated by Django 5.1.3 on 2024-11-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carddistribution',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='card.card'),
        ),
        migrations.AddField(
            model_name='carddistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardflag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='card.card'),
        ),
        migrations.AddField(
            model_name='cardflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardvote',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='card.card'),
        ),
        migrations.AddField(
            model_name='cardvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialcardassetgroup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_groups', to='card.officialcardassetauthor'),
        ),
        migrations.AddField(
            model_name='officialcardasset',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='card.officialcardassetgroup'),
        ),
        migrations.AddField(
            model_name='officialcardassetpurchase',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.officialcardassetgroup'),
        ),
        migrations.AddField(
            model_name='officialcardassetpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercardasset',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_references', to='card.card'),
        ),
        migrations.AddField(
            model_name='usercardasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
