# Generated by Django 5.1.3 on 2025-01-05 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_alter_card_user_alter_usercardasset_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carddistribution",
            name="dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cardvote",
            unique_together={("card", "user")},
        ),
    ]
