# Generated by Django 5.1.3 on 2025-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0004_carddistribution_dismissed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddistribution",
            name="reveal_phase",
            field=models.IntegerField(
                choices=[
                    (0, "Hidden"),
                    (1, "Blurry Strong"),
                    (2, "Blurry Soft"),
                    (3, "Fully Revealed"),
                ],
                default=0,
            ),
        ),
    ]
