# Generated by Django 5.1.3 on 2025-08-06 04:50

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_carddistribution_reveal_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialcardasset',
            name='object_key',
        ),
        migrations.RemoveField(
            model_name='officialcardasset',
            name='public_url',
        ),
        migrations.RemoveField(
            model_name='usercardasset',
            name='object_key',
        ),
        migrations.RemoveField(
            model_name='usercardasset',
            name='public_url',
        ),
        migrations.AddField(
            model_name='officialcardasset',
            name='object',
            field=models.FileField(null=True, upload_to=card.models.official_card_asset_upload_to),
        ),
        migrations.AddField(
            model_name='usercardasset',
            name='object',
            field=models.FileField(null=True, upload_to=card.models.card_asset_upload_to),
        ),
    ]
