# Generated by Django 5.1.3 on 2025-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0006_remove_officialcardasset_object_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="gc_ran_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
