# Generated by Django 5.1.3 on 2025-08-19 07:21

import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0007_card_gc_ran_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardFavoriteItem",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(fields=["card"], name="card_carddi_card_id_6ea1f2_idx"),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(fields=["user"], name="card_carddi_user_id_c0f717_idx"),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(
                fields=["reveal_phase"], name="card_carddi_reveal__eda51e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(
                fields=["dismissed_at"], name="card_carddi_dismiss_bba2c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(
                fields=["deleted_at"], name="card_carddi_deleted_afcd22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(
                fields=["created_at"], name="card_carddi_created_1111a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carddistribution",
            index=models.Index(
                fields=["updated_at"], name="card_carddi_updated_4e59a4_idx"
            ),
        ),
        migrations.AddField(
            model_name="cardfavoriteitem",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="card.card",
            ),
        ),
        migrations.AddField(
            model_name="cardfavoriteitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_collection_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cardfavoriteitem",
            index=models.Index(fields=["user"], name="card_cardfa_user_id_720d58_idx"),
        ),
        migrations.AddIndex(
            model_name="cardfavoriteitem",
            index=models.Index(fields=["card"], name="card_cardfa_card_id_60b363_idx"),
        ),
        migrations.AddIndex(
            model_name="cardfavoriteitem",
            index=models.Index(
                fields=["deleted_at"], name="card_cardfa_deleted_c33f28_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cardfavoriteitem",
            unique_together={("user", "card")},
        ),
    ]
