# Generated by Django 5.1.3 on 2025-08-20 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0008_cardfavoriteitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["user"], name="card_card_user_id_523c27_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["gc_ran_at"], name="card_card_gc_ran__b0bce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["deleted_at"], name="card_card_deleted_d1b05a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["banned_at"], name="card_card_banned__f0f86e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercardasset",
            index=models.Index(fields=["card"], name="card_userca_card_id_79d030_idx"),
        ),
        migrations.AddIndex(
            model_name="usercardasset",
            index=models.Index(fields=["user"], name="card_userca_user_id_58b6fe_idx"),
        ),
        migrations.AddIndex(
            model_name="usercardasset",
            index=models.Index(
                fields=["deleted_at"], name="card_userca_deleted_062a97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercardasset",
            index=models.Index(
                fields=["banned_at"], name="card_userca_banned__331a9b_idx"
            ),
        ),
    ]
