# Generated by Django 5.1.3 on 2025-08-23 10:09

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0009_card_card_card_user_id_523c27_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardflag",
            name="reason",
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=models.Index(fields=["card"], name="card_cardfl_card_id_0d5893_idx"),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=models.Index(fields=["user"], name="card_cardfl_user_id_1f2b30_idx"),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["reason"], name="card_cardfl_reason_7260f7_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=models.Index(
                fields=["resolved_at"], name="card_cardfl_resolve_6e0e36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=models.Index(
                fields=["created_at"], name="card_cardfl_created_b32a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardflag",
            index=models.Index(
                fields=["updated_at"], name="card_cardfl_updated_a1a0ba_idx"
            ),
        ),
    ]
