# Generated by Django 5.1.3 on 2025-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_cardflag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddistribution',
            name='distribution_method',
            field=models.IntegerField(choices=[(0, 'Wave'), (1, 'Chronowave'), (2, 'Wavespot')], default=0),
        ),
    ]
