# Generated by Django 5.1.3 on 2025-01-01 14:57

import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageAttachment",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_key", models.CharField(max_length=2048)),
                ("public_url", models.CharField(max_length=2048)),
                (
                    "thumbnail_key",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("mimetype", models.CharField(max_length=128)),
                ("size", models.IntegerField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messaging.directmessageconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
