# Generated by Django 5.1.3 on 2025-08-06 04:50

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_directmessageattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessageattachment',
            name='object_key',
        ),
        migrations.RemoveField(
            model_name='directmessageattachment',
            name='public_url',
        ),
        migrations.RemoveField(
            model_name='directmessageattachment',
            name='thumbnail_key',
        ),
        migrations.RemoveField(
            model_name='directmessageattachment',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='directmessageattachment',
            name='object',
            field=models.FileField(null=True, upload_to=messaging.models.attachment_upload_to),
        ),
        migrations.AddField(
            model_name='directmessageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=messaging.models.attachment_thumbnail_upload_to),
        ),
    ]
