# Generated by Django 5.1.3 on 2025-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_remove_directmessageattachment_object_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessageattachment",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directmessageattachment",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
