# Generated by Django 5.1.3 on 2025-08-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_directmessageattachment_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessageattachment",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to="messaging.directmessage",
            ),
        ),
    ]
