# Generated by Django 5.1.3 on 2025-08-19 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_directmessageattachment_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="directmessageparticipant",
            unique_together={("conversation", "user")},
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["deleted_at"], name="messaging_d_deleted_32ba36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["created_at"], name="messaging_d_created_900ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["updated_at"], name="messaging_d_updated_9fe08c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageattachment",
            index=models.Index(
                fields=["deleted_at"], name="messaging_d_deleted_0053d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageattachment",
            index=models.Index(
                fields=["created_at"], name="messaging_d_created_43b4c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageattachment",
            index=models.Index(
                fields=["updated_at"], name="messaging_d_updated_281587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageconversation",
            index=models.Index(
                fields=["deleted_at"], name="messaging_d_deleted_83c7f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageconversation",
            index=models.Index(
                fields=["created_at"], name="messaging_d_created_cca7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageconversation",
            index=models.Index(
                fields=["updated_at"], name="messaging_d_updated_f197c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageparticipant",
            index=models.Index(
                fields=["deleted_at"], name="messaging_d_deleted_a09cd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageparticipant",
            index=models.Index(
                fields=["created_at"], name="messaging_d_created_7c10f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageparticipant",
            index=models.Index(
                fields=["updated_at"], name="messaging_d_updated_8e775e_idx"
            ),
        ),
    ]
