# Generated by Django 5.1.3 on 2025-08-20 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_alter_directmessageparticipant_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["conversation"], name="messaging_d_convers_8e2435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["sender"], name="messaging_d_sender__86ec42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageattachment",
            index=models.Index(
                fields=["conversation"], name="messaging_d_convers_4721d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageattachment",
            index=models.Index(
                fields=["sender"], name="messaging_d_sender__bf03cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageconversation",
            index=models.Index(
                fields=["latest_message"], name="messaging_d_latest__7f035d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageparticipant",
            index=models.Index(
                fields=["conversation"], name="messaging_d_convers_80ba9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageparticipant",
            index=models.Index(fields=["user"], name="messaging_d_user_id_377d8a_idx"),
        ),
    ]
