# Generated by Django 5.1.3 on 2025-08-23 02:26

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_directmessage_messaging_d_convers_8e2435_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessageflag",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="directmessageflag",
            name="reason",
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=models.Index(
                fields=["conversation"], name="messaging_d_convers_a148e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=models.Index(fields=["user"], name="messaging_d_user_id_6c4ab0_idx"),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["reason"], name="messaging_d_reason_31911e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=models.Index(
                fields=["resolved_at"], name="messaging_d_resolve_c03428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=models.Index(
                fields=["created_at"], name="messaging_d_created_2e2554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageflag",
            index=models.Index(
                fields=["updated_at"], name="messaging_d_updated_677e49_idx"
            ),
        ),
    ]
