# Generated by Django 5.1.3 on 2025-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_alter_directmessageflag_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessageparticipant",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
    ]
