# Generated by Django 5.1.3 on 2025-08-16 20:09

import flitz.models
import uuid_v7.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="공지사항 제목", max_length=255)),
                ("content", models.TextField(help_text="공지사항 내용")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, help_text="삭제 일시", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="notice_noti_created_b275c9_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="notice_noti_deleted_c96087_idx"
                    ),
                ],
            },
        ),
    ]
