# Generated by Django 5.1.3 on 2024-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="user_user_usernam_6d9439_idx"
            ),
        ),
    ]
