# Generated by Django 5.1.3 on 2024-11-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_user_user_user_usernam_6d9439_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
