# Generated by Django 5.1.3 on 2024-12-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_alter_card_user_alter_usercardasset_type"),
        ("user", "0003_delete_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="main_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="card.card",
            ),
        ),
    ]
