# Generated by Django 5.1.3 on 2025-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_main_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_key",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
