# Generated by Django 5.1.3 on 2025-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userlike_usermatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
