# Generated by Django 5.1.3 on 2025-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_notification_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_hashed",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="UserBlock",
        ),
    ]
