# Generated by Django 5.1.3 on 2025-08-06 04:50

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_phone_number_user_phone_number_hashed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_image_upload_to),
        ),
    ]
