# Generated by Django 5.1.3 on 2025-08-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_user_profile_image_key_and_more"),
        ("user_auth", "0003_alter_usersession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="user_auth.usersession",
            ),
        ),
    ]
