# Generated by Django 5.1.3 on 2025-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_primary_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hashtags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
