# Generated by Django 5.1.3 on 2025-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_user_bio_user_birth_date_user_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
