# Generated by Django 5.1.3 on 2025-08-13 18:17

import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            (0, "Unset"),
                            (1, "Man"),
                            (2, "Woman"),
                            (4, "Non Binary"),
                        ],
                        default=0,
                    ),
                ),
                ("is_trans", models.BooleanField(default=False)),
                ("display_trans_to_others", models.BooleanField(default=False)),
                ("preferred_gender", models.IntegerField(default=0)),
                ("welcomes_trans", models.BooleanField(default=False)),
                ("trans_prefers_safe_match", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
