# Generated by Django 5.1.3 on 2025-08-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_useridentity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useridentity",
            old_name="preferred_gender",
            new_name="preferred_genders",
        ),
    ]
