# Generated by Django 5.1.3 on 2025-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_preferred_gender_useridentity_preferred_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts_blocker_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
