# Generated by Django 5.1.3 on 2025-08-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_user_contacts_blocker_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
