# Generated by Django 5.1.3 on 2025-08-20 22:49

import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("messaging_notifications_enabled", models.BooleanField(default=True)),
                ("match_notifications_enabled", models.BooleanField(default=True)),
                ("notice_notifications_enabled", models.BooleanField(default=True)),
                ("marketing_notifications_enabled", models.BooleanField(default=False)),
                (
                    "marketing_notifications_enabled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="user_userse_user_id_f4d286_idx")
                ],
            },
        ),
    ]
