# Generated by Django 5.1.3 on 2025-08-21 23:44

import django.db.models.deletion
import flitz.models
import user.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedUserArchive",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_user_id",
                    flitz.models.UUIDv7Field(default=uuid_v7.base.uuid7, null=True),
                ),
                (
                    "archived_data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=user.models.deleted_user_archive_upload_to,
                    ),
                ),
                ("delete_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_phase",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "삭제 시작됨"),
                    (1, "민감 정보 삭제됨"),
                    (2, "컨텐츠 삭제됨"),
                    (3, "메시지 삭제됨"),
                    (4, "전체 삭제됨"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_phase_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name="UserDeletionReviewRequest",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.IntegerField(default=0)),
                ("reason_text", models.CharField(max_length=256)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_review_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_userde_user_id_7e6dd0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="user_userde_created_2ec10e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="user_userde_updated_503dce_idx"
                    ),
                ],
            },
        ),
    ]
