# Generated by Django 5.1.3 on 2025-08-22 01:41

import flitz.models
import uuid_v7.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_deleteduserarchive_user_deletion_phase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeletionFeedback",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feedback_text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
