# Generated by Django 5.1.3 on 2025-08-23 10:19

import django.contrib.postgres.indexes
import django.db.models.deletion
import flitz.models
import uuid_v7.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_userdeletionfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlag",
            fields=[
                (
                    "id",
                    flitz.models.UUIDv7Field(
                        default=uuid_v7.base.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.JSONField(default=list)),
                ("user_description", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagged_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_userfl_user_id_495327_idx"
                    ),
                    models.Index(
                        fields=["flagged_by"], name="user_userfl_flagged_ee5e9e_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["reason"], name="user_userfl_reason_44a0d8_gin"
                    ),
                    models.Index(
                        fields=["resolved_at"], name="user_userfl_resolve_affc1c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="user_userfl_created_802f06_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="user_userfl_updated_3dcfdd_idx"
                    ),
                ],
            },
        ),
    ]
