# Generated by Django 5.1.3 on 2025-08-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("card", "0010_alter_cardflag_reason_and_more"),
        ("user", "0020_userflag"),
        ("user_auth", "0004_usersession_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nice_di",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["country"], name="user_user_country_a076ad_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number_hashed"], name="user_user_phone_n_d85933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["nice_di"], name="user_user_nice_di_e0bc7b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["disabled_at"], name="user_user_disable_399fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="user_user_created_c7163e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["updated_at"], name="user_user_updated_2abdb5_idx"
            ),
        ),
    ]
