# Generated by Django 5.1.3 on 2025-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_nice_di_user_user_user_country_a076ad_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['user'], name='user_userid_user_id_0b8a49_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['gender'], name='user_userid_gender_4bf1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['is_trans', 'trans_prefers_safe_match'], name='user_userid_is_tran_4949b8_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['welcomes_trans'], name='user_userid_welcome_d8b9b9_idx'),
        ),
    ]
