# Generated by Django 5.1.3 on 2025-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_useridentity_user_userid_user_id_0b8a49_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useridentity",
            name="gender",
            field=models.PositiveIntegerField(
                choices=[(0, "Unset"), (1, "Man"), (2, "Woman"), (4, "Non Binary")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="useridentity",
            name="preferred_genders",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
